# Generated by Django 2.2.6 on 2019-10-23 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20191023_1319'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WordTuple',
            new_name='Word',
        ),
    ]
