# Generated by Django 2.2.6 on 2019-10-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20191023_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='id',
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
